// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type MonitorBindAddr struct {
	_   structs.HostLayout
	Buf [28]uint8
	Len uint16
}

type MonitorCfg struct {
	_       structs.HostLayout
	SelfPid uint32
}

type MonitorEvent struct {
	_       structs.HostLayout
	TsNs    uint64
	Kind    uint32
	Pid     uint32
	Tid     uint32
	Ppid    uint32
	Uid     uint32
	Comm    [16]int8
	_       [4]byte
	Arg     [6]int64
	Str1Len uint16
	Str2Len uint16
	Str1    [256]int8
	Str2    [256]int8
	_       [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	MonitorMapBindAddrs            = "bind_addrs"
	MonitorMapEventScratch         = "event_scratch"
	MonitorMapEvents               = "events"
	MonitorMapMonitorCfg           = "monitor_cfg"
	MonitorMapSslReadBufs          = "ssl_read_bufs"
	MonitorProgHandleBlockRqIssue  = "handle_block_rq_issue"
	MonitorProgHandleModuleLoad    = "handle_module_load"
	MonitorProgHandleSysEnter      = "handle_sys_enter"
	MonitorProgUprobeGetaddrinfo   = "uprobe_getaddrinfo"
	MonitorProgUprobePgQuery       = "uprobe_pg_query"
	MonitorProgUprobeSslReadEnter  = "uprobe_ssl_read_enter"
	MonitorProgUprobeSslWrite      = "uprobe_ssl_write"
	MonitorProgUretprobeSslReadRet = "uretprobe_ssl_read_ret"
)

// LoadMonitor returns the embedded CollectionSpec for Monitor.
func LoadMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Monitor: %w", err)
	}

	return spec, err
}

// LoadMonitorObjects loads Monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MonitorObjects
//	*MonitorPrograms
//	*MonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMonitorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorSpecs struct {
	MonitorProgramSpecs
	MonitorMapSpecs
	MonitorVariableSpecs
}

// MonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorProgramSpecs struct {
	HandleBlockRqIssue  *ebpf.ProgramSpec `ebpf:"handle_block_rq_issue"`
	HandleModuleLoad    *ebpf.ProgramSpec `ebpf:"handle_module_load"`
	HandleSysEnter      *ebpf.ProgramSpec `ebpf:"handle_sys_enter"`
	UprobeGetaddrinfo   *ebpf.ProgramSpec `ebpf:"uprobe_getaddrinfo"`
	UprobePgQuery       *ebpf.ProgramSpec `ebpf:"uprobe_pg_query"`
	UprobeSslReadEnter  *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_enter"`
	UprobeSslWrite      *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UretprobeSslReadRet *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_ret"`
}

// MonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorMapSpecs struct {
	BindAddrs    *ebpf.MapSpec `ebpf:"bind_addrs"`
	EventScratch *ebpf.MapSpec `ebpf:"event_scratch"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	MonitorCfg   *ebpf.MapSpec `ebpf:"monitor_cfg"`
	SslReadBufs  *ebpf.MapSpec `ebpf:"ssl_read_bufs"`
}

// MonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorVariableSpecs struct {
}

// MonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorObjects struct {
	MonitorPrograms
	MonitorMaps
	MonitorVariables
}

func (o *MonitorObjects) Close() error {
	return _MonitorClose(
		&o.MonitorPrograms,
		&o.MonitorMaps,
	)
}

// MonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorMaps struct {
	BindAddrs    *ebpf.Map `ebpf:"bind_addrs"`
	EventScratch *ebpf.Map `ebpf:"event_scratch"`
	Events       *ebpf.Map `ebpf:"events"`
	MonitorCfg   *ebpf.Map `ebpf:"monitor_cfg"`
	SslReadBufs  *ebpf.Map `ebpf:"ssl_read_bufs"`
}

func (m *MonitorMaps) Close() error {
	return _MonitorClose(
		m.BindAddrs,
		m.EventScratch,
		m.Events,
		m.MonitorCfg,
		m.SslReadBufs,
	)
}

// MonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorVariables struct {
}

// MonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorPrograms struct {
	HandleBlockRqIssue  *ebpf.Program `ebpf:"handle_block_rq_issue"`
	HandleModuleLoad    *ebpf.Program `ebpf:"handle_module_load"`
	HandleSysEnter      *ebpf.Program `ebpf:"handle_sys_enter"`
	UprobeGetaddrinfo   *ebpf.Program `ebpf:"uprobe_getaddrinfo"`
	UprobePgQuery       *ebpf.Program `ebpf:"uprobe_pg_query"`
	UprobeSslReadEnter  *ebpf.Program `ebpf:"uprobe_ssl_read_enter"`
	UprobeSslWrite      *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UretprobeSslReadRet *ebpf.Program `ebpf:"uretprobe_ssl_read_ret"`
}

func (p *MonitorPrograms) Close() error {
	return _MonitorClose(
		p.HandleBlockRqIssue,
		p.HandleModuleLoad,
		p.HandleSysEnter,
		p.UprobeGetaddrinfo,
		p.UprobePgQuery,
		p.UprobeSslReadEnter,
		p.UprobeSslWrite,
		p.UretprobeSslReadRet,
	)
}

func _MonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed monitor_x86_bpfel.o
var _MonitorBytes []byte
